- name: create isutrain directory
  file: path="/home/isucon/isutrain" state=directory mode=0644 owner=isucon group=isucon
  tags: challenge

- name: copy files
  unarchive: src="webapp.tar.gz" dest=/home/isucon/isutrain/ owner=isucon group=isucon
  tags: challenge

- name: create systemd services
  template: src=isutrain.service dest="/etc/systemd/system/isutrain-{{ item }}.service" owner=root group=root mode=0644
  with_items:
    - go
  tags: challenge
  notify: systemctl daemon-reload
